[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino

; ----- Particiones personalizadas (OTA dual bank) -----
board_build.partitions = partitions_ota.csv

; ----- Velocidad de comunicación serial -----
monitor_speed = 115200

; ----- Librerías -----
lib_deps =
    arduino-libraries/Ethernet@^2.0.2
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
    ESP_SSLClient=https://github.com/mobizt/ESP_SSLClient

; ----- Flags de compilación -----
build_flags =
    -DCORE_DEBUG_LEVEL=3
